### ISSUE TITLE
[dired-subtree] [Feature Request] C-x C-f in nested tree

### ISSUE THREAD

**Issue by jojojames** [Fuco1/dired-hacks#100]
When using dired-subtree and cycling the trees, it'd be great if commands like C-x C-f work with the point.

```
.emacs.d <------- uses .emacs.d directory
|
|
| <--- uses .emacs.d directory
> snippets <------- defaults to snippets directory
|
|
|
|
| <------------------ defaults to snippets directory
>> org-mode <--------- defaults to org directory
|
|
|
|
|
| <-------- defaults to org directory
```

Something like this?^

**Comment by Fuco1** [comment]
It does work for me as you describe.

Turns out I have redefined the `C-x C-f` command to this:

```elisp
(defun my-dired-ido-find-file ()
  "Like `ido-find-file' but with `default-directory' set to the
one specified by listing header."
  (interactive)
  (let ((default-directory (dired-current-directory)))
    (ido-find-file)))
```

This can't be done magically without some sort of redefinition, so you can just use the above function I guess.  If you don't use `ido` replace the ido function with the regular version (`find-file`).

**Comment by jojojames** [comment]
Thanks! I will use that function.
