### ISSUE TITLE
[dired-collapse] Can't visit root directory because of permission error

### ISSUE THREAD

**Issue by jojojames** [Fuco1/dired-hacks#101]
```
Debugger entered--Lisp error: (file-error "Opening directory" "Permission denied" "/.DocumentRevisions-V100")
  directory-files("/.DocumentRevisions-V100" t)
  f--collect-entries("/.DocumentRevisions-V100" nil)
  f-entries("/.DocumentRevisions-V100")
  dired-collapse()
  run-hooks(dired-after-readin-hook)
  dired-readin()
  dired-internal-noselect("/" nil)
  dired-noselect("/" nil)
  dired("/")
  dired-up-directory()
```

Looks like f throws an error upon looking at folders without the proper permissions. Disabling dired-collapse and visiting / normally works as expected.

**Comment by Fuco1** [comment]
Hi, thanks for the report!

I think this has already been reported in this thread: https://github.com/Fuco1/dired-hacks/issues/99 And we also opened an issue in the `f.el` repository.  We think that the `f` utility should skip the files without read permissions (or gather them somehow silently for further inspection).

**Comment by jojojames** [comment]
Hmnn, thanks, I'll watch the f bug report then!

**Comment by Fuco1** [comment]
I'm going to close this in favour of the other bug report.  I think I will solve it on our side, because sometimes you might have read permissions for directories but not files inside etc, so we can probably add some logic for that.
