### ISSUE TITLE
[dired-collapse] [dired-subtree] Collapsed directories aren't shown when using dire-subtree

### ISSUE THREAD

**Issue by naclander** [Fuco1/dired-hacks#103]
I just recently started using both of these plugins together, and I've noticed that when `dired-collapse-mode` is enabled, I can't seem to see collapsed directories in directories that have been expanded using dired-subtree. 

I have to disable and enable `dired-collapse-mode` if I want to see them again. It would be great if `dired-collapse-mode` would work under this situation. 

Thanks for all the work you've done this set of pacakges so far, its definitely made my life using Dired better.

**Comment by Fuco1** [comment]
Oh yes, `dired-collapse` uses `dired-after-readin-hook` but `dired-subtree` only calls `dired-subtree-after-insert-hook`.  I think that we could call `dired-collapse` somewhere at the end of `dired-subtree-insert`, but probably in a narrowed buffer so it wouldn't rescan the whole buffer.

**Comment by naclander** [comment]
Cool, I can potentially take a look at that. This should probably also only be done if we detect that `dired-collapse` is installed.

**Comment by naclander** [comment]
@Fuco1 on closer look, other than potential performance implications, is there a reason you don't want to add:

`(add-hook 'dired-subtree-after-insert-hook 'dired-collapse 'append 'local)` [here](https://github.com/Fuco1/dired-hacks/blob/master/dired-collapse.el#L82)?

I've verified this works for me. I see what you mean about the potential downside of scanning the whole buffer again but I feel in most situation this wouldn't be an issue.

**Comment by Fuco1** [comment]
I think we can do that.
