### ISSUE TITLE
Filter by git-ignored-files / files-unknown-from-git

### ISSUE THREAD

**Issue by Silex** [Fuco1/dired-hacks#11]
Pretty much self-explanatory, would be nice I think.

**Comment by felixSchl** [comment]
This would be awesome to have. I've been using the wonderful vimfiler plugin for vim but the biggest problem with it in my workflow was the excruciatingly slow `.gitignore` based filter. Maybe whatever comes out of this could theoretically be applied to vimfiler as well, which would be double awesome.

**Comment by Fuco1** [comment]
@felixSchl can you maybe point me to the vim extension?  I'm quite interested in how they do it.  My basic idea was to run `git ls-files` first and then query that to see if the file should be ignored or not.

**Comment by felixSchl** [comment]
Yeah of course, the plugin lives here: https://github.com/Shougo/vimfiler.vim. The docs also mention it's slow here: https://github.com/Shougo/vimfiler.vim/blob/master/doc/vimfiler.txt#L1105-L1107

**Comment by matthewbauer** [comment]
@jwiegley has some code to do this:

http://newartisans.com/2008/08/omitting-git-ignored-files-in-emacs-dired/

Maybe take that code and rework it to use advice-add?

**Comment by Fuco1** [comment]
I've added `git-ignored` filter, you can use it under `ig` (ignore -> git).

I'll add one for unknown files as well but first I want to do some refactoring to make things less ugly.

**Comment by Thaodan** [comment]
On a related note should dired apply filter from xdg directory files? E.g. hidden files.

**Comment by Fuco1** [comment]
@Thaodan I don't understand your question, it seems not related to git.  Can you open a new issue?
