### ISSUE TITLE
[dired-collapse] Empty folders?

### ISSUE THREAD

**Issue by dieggsy** [Fuco1/dired-hacks#113]
I'm not sure what the right way to go about this is, but right now in `dired-collapse` empty folders look the same as folders with more than one file. It would be nice if they were shadowed out as well, or there was some indication that they're empty. It could save the user going in and out of a folder that has nothing, or indicate that it's safe to delete. This seems like it's within the scope of what the packages tries to accomplish.

**Comment by Fuco1** [comment]
That's a good idea, I like it!  It should be simple to implement as well, we would just test the folder and if it's empty extend the overlay to the end of line.

Do you want to try your hands on it? :) If not that's fine of course, ideas matter too!

**Comment by dieggsy** [comment]
So I played with it for a bit, don't think I'm quite sure how to do it.

**Comment by Fuco1** [comment]
This code is where the change needs to happen, we just need to extend the `end` variable to the end of line if the directory is empty.

https://github.com/Fuco1/dired-hacks/blob/f4f2f3ade3b592502b8336bc9d10288ae00679ad/dired-collapse.el#L125-L130

The path to the directory should be in the variable `path`.  I'll have a look sometime, probably tomorrow, but if the above hints help go ahead ;)

**Comment by dieggsy** [comment]
I thought that's what you were referring to, but stepping through the function it actually doesn't hit that `(when (string-match-p "/" path) ...)` block

**Comment by Fuco1** [comment]
/shrug might be, I've done some refactoring lately.  I should add some tests too :)

Fair enough, I'll have a look.  I quite like the proposal so it will be sooner than later :heart:

**Comment by Fuco1** [comment]
This is now available on master, will be on Melpa in couple hours when they trigger a build.

**Comment by dieggsy** [comment]
@Fuco1 great, thanks!
