### ISSUE TITLE
[dired-rainbow] Highlight marked files

### ISSUE THREAD

**Issue by igorepst** [Fuco1/dired-hacks#117]
Hello @Fuco1,
Is it possible to prefer in-built highlight for marked files (`dired-marked-face`) over highlight by extension?
Thanks

**Comment by Fuco1** [comment]
It works for me as you want, I suppose this is the desired result?

![](https://i.imgur.com/pm548zx.png)

Can you give me a screenshot of what you get?

**Comment by igorepst** [comment]
Hi, I still have a problem when checked with `emacs -q` and loading this:
```
(add-to-list 'load-path "~/.emacs.d/elpa/")
  (let ((default-directory "~/.emacs.d/elpa/"))
    (normal-top-level-add-subdirs-to-load-path))
(require 'dired-rainbow)
(defconst ig-exec-files-extensions '("bat"))
(dired-rainbow-define ig-exec-files-extensions "red" ig-exec-files-extensions)
```
Without marking:
![image](https://user-images.githubusercontent.com/1630792/33517013-dfbc8f66-d784-11e7-9a1a-fc2187121217.png)
With marking:
![image](https://user-images.githubusercontent.com/1630792/33517021-075b97a6-d785-11e7-8069-b8d8d806c8c6.png)

**Comment by igorepst** [comment]
I solved my problem by using an optional argument `how` to `font-lock-add-keywords`. 
Example:
`(dired-rainbow-define ig-exec-files-extensions "red" ig-exec-files-extensions t)`

Would you like a PR?

**Comment by Fuco1** [comment]
So it seems things depend on the load order.  Yea, a PR is very welcome!

**Comment by igorepst** [comment]
I opened the PR. Things indeed depends on the load order. I tried to resolve it by moving `(require 'dired-rainbow)` to `config` or `init` of `use-package dired`, but it didn't fix it.
Thanks for your help!
