### ISSUE TITLE
dired-subtree - keep hl-line visible?

### ISSUE THREAD

**Issue by dieggsy** [Fuco1/dired-hacks#120]
Is there a way to keep the line from hl-line visible when point is at a subtree? I'm not sure what the right way of going about this is.

**Comment by Fuco1** [comment]
`hl-line-mode` sets the overlay priority to -50 which indicates to me the author wants that overlay to be on the bottom of all the others.  We can't do anything about it.

```
  face                 hl-line
  priority             -50
```
