### ISSUE TITLE
dired-filter-saved-filters

### ISSUE THREAD

**Issue by wpasieka** [Fuco1/dired-hacks#121]
The variables are added into (dired-filter-saved-filters), and placed into a customized file, which works o'k.

At the moment I am using dired-filter-add-saved-filters each time when starting emacs, but some of these settngs, like omiting the dots, could be made permanent.

Possibly by placing something into the emacs init - maybe there is a solution, please advice.

Or by adding an additional variable to the dired-filter-saved-filters, when saving a template , like "run at start", which could be removed in the custom file, in a standard way.

**Comment by Fuco1** [comment]
If you want to have a specific filter active by default every time you enter dired you can customize `dired-filter-stack` variable.  That is the one where the "active" filters for each dired buffer are stored (it is separate for every buffer but starts with a default value).

**Comment by Fuco1** [comment]
- [ ] Document the configuration `dired-filter-stack` in readme
