### ISSUE TITLE
Need a hook to tell if a normal file is opened.

### ISSUE THREAD

**Issue by amosbird** [Fuco1/dired-hacks#123]
Hi, I'm using both dired-open and peep-dired. I'd like to disable peep-dired when a normal file is opened and dired window is gone.

**Comment by dvzubarev** [comment]
How did you solve this problem?

**Comment by amosbird** [comment]
By rewriting it  :)   https://github.com/amosbird/abdoom/blob/master/autoload/amos-dired.el
