### ISSUE TITLE
dired-subtree-insert works perfectly on local files but fails on remote with TRAMP.

### ISSUE THREAD

**Issue by fabman** [Fuco1/dired-hacks#127]
After working locally on some folders without a hitch I tried dired-subtree-insert on a remote folder through TRAMP, getting on the mini-buffer:

`Symbol's function definition is void: tramp-sh-handle-file-directory-p`

os:  Windows 10 pro
dired-subtree Package-Version: 20170910.1521
tramp-version 2.2.13.25.2

**Comment by Fuco1** [comment]
I have the same version of tramp and the function is defined.  I suspect this is a windows issue as `sh` suggests `/bin/sh` to me which is probably not available.

I did not write that code and don't really know how to replace the call.  We can guard against the OS to at least not error out, but then the thing will not work anyhow.

**Comment by fabman** [comment]
Is pretty strange because I tried with the same .emacs.d folder on one of my linux vps and still got the same error. 

`Symbol's function definition is void: tramp-sh-handle-file-directory-p`

![image](https://user-images.githubusercontent.com/743556/37362379-4cd28820-26f5-11e8-932f-4198b1169005.png)

os: debian 8
dired-subtree Package-Version: 20170910.1521
tramp-version 2.2.13.25.2

**Comment by fabman** [comment]
Now it works with TRAMP, but not perfectly. It seems to leave out always the first file on the list of the sub directory.

![image](https://user-images.githubusercontent.com/743556/46863201-064bca00-ce17-11e8-90b3-3a36503ac760.png)
