### ISSUE TITLE
Add dired-hacks-utils as a dependency for dired-collapse

### ISSUE THREAD

**Issue by kaushalmodi** [Fuco1/dired-hacks#133]
Hello,

I use your dired-collapse package. But after its last update, I started getting an error saying that dired-hacks-utils was not found.

It was because updating dired-collapse did not auto-install dired-hacks-utils.

This can be fixed by adding `dired-hacks-utils` to the *Package-requires* line [here][1].

[1]: https://github.com/Fuco1/dired-hacks/blob/2aeee2c2087c15062a14ed496831bd563a82b8c7/dired-collapse.el#L9

**Comment by Fuco1** [comment]
Oh dang you are right, I did the change but forgot to update the dependencies!  On it right away.

**Comment by Fuco1** [comment]
Hopefully this will pop up on MELPA soon.
