### ISSUE TITLE
Running `dired-find-file` (`RET`) on a file under `~/.avfs` causes Emacs to lock up

### ISSUE THREAD

**Issue by jpkotta** [Fuco1/dired-hacks#136]
This is very easy to do with #76.  The only thing I can do is send the process SIGKILL.

**Comment by Fuco1** [comment]
That's probably an issue with the avfs mount more than with Emacs.  There is nothing special except opening the file which then goes right through the system.

Can you access those files from the command line? If so then we can be a bit more sure this is caused by Emacs or this package.

**Comment by jpkotta** [comment]
Yeah, it's not just Emacs, because `cat`ting a file always hangs and sometimes needs SIGKILL (and even then sometimes that doesn't work).  It's also nothing directly to do with this package, because you can lock up `emacs -Q`.  Ideally it would be impossible to try to open files under `~/.avfs`; if it's easy to do this somehow it would be a good idea.

**Comment by Fuco1** [comment]
Are you using `dired-avfs` to open them?  In which case, if your `avfs` daemon is not working maybe not using that package would be easier solution.  As it is quite hard to wander into `~/.avfs` by accident.

**Comment by jpkotta** [comment]
I originally wandered into ~/.avfs due to #76, otherwise I've been just testing things by going directly in there with dired.
