### ISSUE TITLE
Cannot kill buffer: “Marker does not point anywhere”

### ISSUE THREAD

**Issue by ChoppinBlockParty** [Fuco1/dired-hacks#141]
For some reasons I hit the error in `dired-current-directory`. Please, see [this stackoverflow question](https://stackoverflow.com/questions/52724679/cannot-kill-buffer-marker-does-not-point-anywhere) for more details.

**Comment by ChoppinBlockParty** [comment]
yup I know, that was just a guess, I mean it ends up in `dired-current-directory` that is part of `dired-subtree.el`. Look at the stack trace.

**Comment by Fuco1** [comment]
It's probably something broken in the integration of subtree to the sidebar package. @jojojames any ideas here?

**Comment by jojojames** [comment]
I haven't seen it myself but I think I've ran into similar issues in the past. Can you create a minimal repro and report an issue @ChoppinBlockParty ?

**Comment by ChoppinBlockParty** [comment]
Very hard to reproduce. I reproduced it once, then failed to reproduce it again. But it somehow all around the following flow.

* I open a bar in `A` directory.
* Call `dired-view-file` on some child directories of it (this opens a dired buffer outside the bar).
* Close the bar, choose a file from the dired buffer. This file is located in some project.
* I open a bar again, it opens a child directory `B` of directory `A`.
* I repeat the steps again an somehow its stuck.

I thinks the main problem that at the end I have two or more dired-sidebar buffers, it also could be relevant to opening sidebar buffers inside a regular window, not really on a side.

If I find anything more I will tell you.

**Comment by jojojames** [comment]
Please open an issue on the dired-sidebar github if you do @ChoppinBlockParty ! I'd greatly appreciate it, if not just for tracking purposes. (I'm also tracking this thread.)
