### ISSUE TITLE
`dired-filter-group-toggle-header` is showing dired details when expanding

### ISSUE THREAD

**Issue by deescuderoo** [Fuco1/dired-hacks#146]
Sorry, I'm a newbie when it comes to customizing Emacs. 

I'm hiding the details in dired by default
```
(add-hook 'dired-mode-hook '(lambda () (interactive) (dired-hide-details-mode 1)))
```
but when I filter groups, collapse, and expand, then details appear. For example, this is a folder before collapsing/expanding:
```
 [ PDF ]
 main.pdf
```
then I place the cursor on `[PDF]` and hit `RET`, so I get
```
 [ PDF ... ]
```
but, if I press `RET` again, I get this
```
 [ PDF ]
  -rw-rw-r--  1 XYZ XYZ 181330 Feb  7 21:14 main.pdf
```
that is, details are shown again. 

Any ideas about what could be going on? I don't know what to do. I tried calling `revert-buffer` after expanding but this one expands everything, not only the group I'm interested in.

Thanks!

**Comment by Fuco1** [comment]
Yea I can confirm this is happening.  We are really naive when it comes to invisibility spec.  This should be an easy fix though.

**Comment by Fuco1** [comment]
I've fixed the problem, it will build on Melpa in a couple hours or you can apply the patch manually.

**Comment by deescuderoo** [comment]
Thanks a lot @Fuco1! That was very fast.

I have downloaded the file and repaced the old one by this one. Now I'm getting this error at launch:
```
Error (use-package): dired-filter/:catch: Required feature ‘indent’ was not provided
```
Sorry if that's a silly mistake from my side.

**Comment by Fuco1** [comment]
Silly me, that file is loaded automatically.  I'll fix it right away.

**Comment by Fuco1** [comment]
It's in master now.  You can also just open the `dired-filter.el` file and remove the `(require 'indent)` line, it's right there after the description part.

**Comment by deescuderoo** [comment]
Yay! Now it works. Thanks a lot @Fuco1.
