### ISSUE TITLE
[dired-rainbow] read color from "config"

### ISSUE THREAD

**Issue by azzamsa** [Fuco1/dired-hacks#158]
I have an idea/feature request. What if we give dired-rainbow an ability to read colors from "config" files. The benefit are:

- we can specify "theme" in those configs
- we can grow the "filetypes" in those config.

I am inspired by the approach of [vivid](https://github.com/sharkdp/vivid). vivid has [themes](https://github.com/sharkdp/vivid/tree/master/themes) and [filetypes](https://github.com/sharkdp/vivid/blob/master/config/filetypes.yml)

I've converted one of vivid theme [to elisp list](https://gist.github.com/azzamsa/27ed28d7de379173061bf68d8e9798c8) with it's [filetypes](https://gist.github.com/azzamsa/5a13a53a6b76a5cb672cc5c793035c39)

So instead of putting all of them in `:cofig` like we have now. we can do:

before

```elisp
(use-package dired-rainbow
  :after dired
  :config
  (dired-rainbow-define-chmod executable-unix "#77e323" "-.*x.*")
  (dired-rainbow-define sourcefile "#b4fa70" ("py" "cl" "el" "ruby" "java"
                                              "html" "xml"))
  (dired-rainbow-define encrypted "#ffcc5c" ("gpg" "pgp")))

```

```elisp
(use-package dired-rainbow
  :after dired
  :config
  (setq dired-rainbow-theme "molokai"))
```

It make them easier to change theme based on what machine they are using too.

```elisp
(if (eq system-type 'windows-nt)
    (setq dired-rainbow-theme "molokai")
  (setq dired-rainbow-theme "ayu"))
```

Thanks in advance.

**Comment by Fuco1** [comment]
Why not.  I'd not use a file but instead some function/data structure we put in the init file.  I think this could be implemented easily with just some macro that would generate the appropriate define statements.
