### ISSUE TITLE
Dired-narrow disappears after using  dired-toggle-read-only

### ISSUE THREAD

**Issue by ghost** [Fuco1/dired-hacks#166]
I combine dired-narrow (C-x /) with dired-toggle-read-only (C-x C-q) which allows me to edit dired file names. However, if I press C-c C-c to commit my changes after using dired-toggle-read-only this also makes dired-narrow disappear. I would like the dired-narrow view to remain until I press "g".

**Comment by Fuco1** [comment]
dired-narrow uses quite fragile minibuffer hack to process the input incrementally.  Might be that switching the window and read-only state toggles exit which breaks out of the editing state.

It's probably fixable but, hmm.  Maybe using dired-filter would be easier :D  What's your workflow?

**Comment by revrari** [comment]
I have had some problems setting up dired-filter. I would like to use dired-narrow as it is simple and a mainstay of my workflow.

**Comment by revrari** [comment]
I have managed to get dired-filter to work and its awesome.

**Comment by revrari** [comment]
FYI
[https://emacs.stackexchange.com/questions/54721/dired-narrow-view-disappears-after-using-dired-toggle-read-only]
