### ISSUE TITLE
[dired-subtree] dired-subtree-insert caused clickable area to extend to entire line

### ISSUE THREAD

**Issue by jusw85** [Fuco1/dired-hacks#167]
1. Before dired-subtree-insert
![Screenshot from 2020-03-26 20-36-32](https://user-images.githubusercontent.com/3406652/77647672-cbedd280-6fa1-11ea-94d8-6df374c1bbb7.png)
2. After dired-subtree-insert
![Screenshot from 2020-03-26 20-37-06](https://user-images.githubusercontent.com/3406652/77647679-cee8c300-6fa1-11ea-9924-d70bf7780864.png)
3. After dired-subtree-remove
![Screenshot from 2020-03-26 20-37-17](https://user-images.githubusercontent.com/3406652/77647685-d019f000-6fa1-11ea-90e6-d1c399dd3606.png)

After dired-subtree-insert, clicking anywhere in the empty space on the right of the file will have the same effect as clicking directly on the file itself.

I fixed it by changing the following line to `(insert "\n")`.

https://github.com/Fuco1/dired-hacks/blob/f49a8bbf95f70671a74a24f7f4de453b2686be46/dired-subtree.el#L498

**Comment by Fuco1** [comment]
Probably some text properties there are set to be sticky which newline then "extends".  Would you like to make a pull request?  I think your fix is appropriate!
