### ISSUE TITLE
dired-subtree-toggle puts point at the beggining of buffer instead of at first directory

### ISSUE THREAD

**Issue by amno1** [Fuco1/dired-hacks#170]
My use case: dired is sorting directories first and I use dired-subtree-toggle (bound to the tab key) quite a lot! If I have toggled very first directory in a dired buffer, when I "toggle back" (remove the subtree), the point is put at the (point-min), which is very first character in dired buffer. It means the point after toggling the first directory is put at the very first line in buffer which is name of that dired buffer; even two chars before the name. If I wish to go back to first directory in the buffer or to next directory I have to press 'n'.

That is easily fixed; we just need a check for beggining of buffer and to move the point one line forward if the check evals to true (in dired-subtree-toggle function):
```
                                  (if (bobp)
                                      (dired-next-line 1))
```

Here is the hacked function:

```
            (defun dired-subtree-toggle ()
                   "Insert subtree at point or remove it if it was not present."
                   (interactive)
                   (if (dired-subtree--is-expanded-p)
                           (progn
                                  (dired-next-line 1)
                                  (dired-subtree-remove)
                                  (if (bobp)
                                      (dired-next-line 1)))
                       (save-excursion (dired-subtree-insert))))
```
 It is not very important issue, but I find it to be a small annoyance, and it bothered me for ages (!) since I do quite often toggle the first directory in the list. I never come around to fix it, but today I did :-). I hope it is useful to others, but if it is considered a non-issue, then please just close/delete this post.

**Comment by mtreca** [comment]
I was a bout to post a similar issue and saw yours. Great fix, I would be interested in seeing this merged as well.

**Comment by amno1** [comment]
> I was about to post a similar issue and saw yours. Great fix, I would be interested in seeing this merged as well.

Cool if it helps you. Here is slightly prettier version (removes unnecessary progn-block):

```
 (defun dired-subtree-toggle ()
     "Insert subtree at point or remove it if it was not present."
     (interactive)
     (when (dired-subtree--is-expanded-p)
       (dired-next-line 1)
       (dired-subtree-remove)
       (when (bobp)
         (dired-next-line 1))
       (save-excursion (dired-subtree-insert)))))
```

**Comment by amno1** [comment]
I added a PR, so whichever Fuco prefers, if he likes the solution :-).
