### ISSUE TITLE
Upstreaming?

### ISSUE THREAD

**Issue by alphapapa** [Fuco1/dired-hacks#173]
Hi Matus,

I searched the issues, but I couldn't find any issues discussing upstreaming into Emacs.  Have you considered trying to get some of these upstream?  I think that, e.g. `dired-subtree` and `dired-collapse` would be especially suitable for including in Dired proper.

Thanks for your work on these tools.

**Comment by Fuco1** [comment]
I personally won't do it but the code is under GPL to use and I have the Emacs paperwork.
