### ISSUE TITLE
Auto increment file name if same name exists

### ISSUE THREAD

**Issue by azzamsa** [Fuco1/dired-hacks#174]
Hi.

The default behavior of regular file manager (Thunar, Dolphin, etc) is to increment file name if the same name exists.

Case:

``` txt
linode.png
linode (copy 1).png
```

If I copy `linode.png` in the same directory, then the resulting copy will have a trailing `(copy 1)`.

I would like to add this functionality to [dired-ranger-paste](https://github.com/Fuco1/dired-hacks/blob/d6d4d1930969bbc22fd0551d5195887bf92cab3e/dired-ranger.el#L167). But now I am thinking:

- if this should be the default
- can it use the `arg` for toggle
- or should it take a value from the configuration variable

What your thoughts on this?

If you reject this idea. I would like to implement this on my side only.

**Comment by Fuco1** [comment]
I think this is a nice feature.

By default we now ask if you want to overwrite the file.  We can instead change this to a multi-option menu, where we can ask:

- do nothing
- overwrite
- insert a (copy 1)

Additionally, we can add a setting where you can set the default answer to this question. (i.e. overwrite without asking or add the `copy X`).  `map-y-or-n-p` can be used to ask a question with multiple actions bound to keys.

**Comment by azzamsa** [comment]
> By default we now ask if you want to overwrite the file. We can instead change this to a multi-option menu, where we can ask:
> 
>     * do nothing
> 
>     * overwrite
> 
>     * insert a (copy 1)

affirmative :+1:

**Comment by azzamsa** [comment]
I use Dired-Ranger nowadays and it has auto-increment out of the box.

Thanks for Dired-hacks.
