### ISSUE TITLE
Cannot visit files under subtree

### ISSUE THREAD

**Issue by tuhdo** [Fuco1/dired-hacks#19]
It shows this error:

> dired-get-file-for-visit: No file on this line

Emacs version:

> GNU Emacs 24.3.93.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2014-09-06 on tuhdo-MacBookAir

**Comment by Fuco1** [comment]
I can't reproduce this.  Do you use some other dired-related packages?

**Comment by tuhdo** [comment]
Yes, I reproduced it from `emacs -q`:

1. Add MELPA.
2. Install `dired-subtree` from MELPA.
3. Open a Dired buffer, move point to a directory in that Dired buffer.
4. Run `dired-subtree-insert`.
5. Press `RET` or `o`.
6. Error:

```text
Debugger entered--Lisp error: (error "No file on this line")
  signal(error ("No file on this line"))
  error("No file on this line")
  dired-get-file-for-visit()
  dired-find-file()
  call-interactively(dired-find-file nil nil)
  command-execute(dired-find-file)
```
