### ISSUE TITLE
dired-list not in MELPA

### ISSUE THREAD

**Issue by aagon** [Fuco1/dired-hacks#195]
Hello,

First of all, thank you for these very useful packages. I noticed that dired-list is not in MELPA, despite being mentioned in the README, and therefore present in package repositories, according to the third paragraph of the README.

For this reason, I guess it must be a mistake.

Do you want me to create a PR on the melpa repository ?

Best,

Aymeric

**Comment by Fuco1** [comment]
https://github.com/melpa/melpa/pull/8424
