### ISSUE TITLE
dired-subtree displayed as empty when it contain only a file/folder

### ISSUE THREAD

**Issue by bricewge** [Fuco1/dired-hacks#20]
If ``(setq dired-listing-switches "-Al")`` is set with the switch ``-A`` witch hide ``.`` and ``..``, when ``dired-subtree-insert`` is used on a folder containing only one file or one folder, a subtree of one empty line open in the buffer.
This doesn't appear when the switch used is ``-a``, the name of the folder/file is correctly written.

**Comment by Fuco1** [comment]
I see why now... it's because I delete the first two line where I assume the `.` and `..` to be always present.  We need to add a check if the first two lines are useless or not.

**Comment by Fuco1** [comment]
Fixed in df9b47b

**Comment by bricewge** [comment]
Thanks for the fix! It's now working well on my side. (:
