### ISSUE TITLE
dired-list-find-file : if: Symbol’s value as variable is void: dir

### ISSUE THREAD

**Issue by aagon** [Fuco1/dired-hacks#206]
Commit d922df8 broke function `dired-list-find-file` : variable `dir` is used at line [338](https://github.com/Fuco1/dired-hacks/blob/0b2c7a1a232438267c908b60fabd85c3fa33dc8f/dired-list.el#L338C29-L338C29) despite being set only at line [340](https://github.com/Fuco1/dired-hacks/blob/0b2c7a1a232438267c908b60fabd85c3fa33dc8f/dired-list.el#L340C1-L340C1).

The steps to reproduce in `emacs -Q` are quite straightforward : 

```elisp
(package-initialize)
;; Fix these
(load "/path/to/dash.el")
(load "/path/to/dired-hacks-utils.el")
(load "/path/to/dired-list.el")
```

And then run `M-x dired-list-find-file`, you should see the error `if: Symbol’s value as variable is void: dir` appear.

Best,

Aymeric Agon-Rambosson

**Comment by Fuco1** [comment]
Thanks, fixed.
