### ISSUE TITLE
dired-subtree not compatible with dired-hide-details-mode from Emacs 24.4

### ISSUE THREAD

**Issue by danskarda** [Fuco1/dired-hacks#30]
Last Emacs version adds new capability to dired to hide file details (flags, owner and date). 

`dired-subtree` is not compatible with `dired-hide-details-mode` when details are hidden.

I found more implementations of this feature (dired+, dired-details). I guess compatibility with Emacs 24.4 implementation would be enough.

**Comment by Fuco1** [comment]
Someone mailed me about this issue recently, here I quote my reply

>> I think if `dired-subtree-insert' inserts hide-detailed subtree, that would be ideal.  Please consider implementation!

> Instead of implementing this directly, I've added two hooks: one which
runs after `dired-subtree-insert` and one after `dired-subtree-remove`.
You can add some code to refresh the hide-detail overlays there.  I'm
still on 24.3 and I use `dired-details` package, the following code
properly refreshes the overlays:

    (add-hook 'dired-subtree-after-insert-hook 
          (lambda ()
            (dired-details-delete-overlays)
            (dired-details-activate)))

> You might need a slightly different lambda with 24.4 and its built-in
mode, but it should be fairly simple to figure out.

If you find some way to do this, let me know so we can add it as a default option.

**Comment by dzop** [comment]
For 24.4 and above it looks like the details are hidden with text properties and not overlays. The lambda should be:
```emacs-lisp
(add-hook 'dired-subtree-after-insert-hook
          '(lambda ()
             (let ((inhibit-read-only t))
               (dired-insert-set-properties (point-min) (point-max)))))
```

Though it would be better to use `dried-subtree--get-ov` to get the bounds of the subtree and just change the text properties of the subtree only.

**Comment by Fuco1** [comment]
Hm, it should probably be done in some backward-compatible way, invoking one or the other depending on what version the user runs.

Do you think you could provide a PR for this? (that is, if you want to)

**Comment by glucas** [comment]
Not sure if it is the same issue, but `dired-narrow` doesn't interact well with `dired-hide-details-mode` either. As soon as you call one of the `dired-narrow` commands, the details are shown.

**Comment by Fuco1** [comment]
@glucas Probably.  It stopped working for me completely, no narrowing happens at all, in addition to showing details.  Please start a seprate issue for this.

**Comment by bricewge** [comment]
Thanks @dzop for fixing this issue!
What about closing this bug?

**Comment by Fuco1** [comment]
Sure, closing.  Thanks for the reminder ;)
