### ISSUE TITLE
Please consider adding an "umbrella" library `dired-hacks.el'

### ISSUE THREAD

**Issue by tarsius** [Fuco1/dired-hacks#31]
I have brought this up elsewhere but the context was confusing so I'll try again and go into more detail.

While some of the libraries in this repository are required by others, most of the libraries can be used independently of one another. Compared to other extensions to `dired` this is a big advantage of yours, as users can mix and match as they see fit. Never-the-less these libraries are closely related to one-another and so it makes a lot of sense to keep them in a single repository.

Most people nowadays install their elisp libraries using `package.el`. And because most users probably don't want all of these fine libraries they were split into separate packages which can be installed independently.

Others however prefer to install packages by adding them as submodules of their `user-emacs-directory` which they track in git. I do it for example, mostly because it makes it much easier to contribute back to the packages I use. I can instantly start doing so, the repository is already cloned and I do not need to fiddle with the `load-path` to ensure the version I am working on gets loaded.

That can be a problem when upstream puts unrelated things into the same repository. However that is not the case here. I think it is perfectly fine, or rather even preferable, to have all these libraries in the same repository. After all, just because they are on the `load-path` I don't have to actually load them.

So the suggestion I have to make is a rather cosmetic and not very important one.

The Emacsmirror collects Emacs packages, but the basic unit is the repository. When a repository contains unrelated stuff, then that is an issue. But in this case it is not because the libraries _are_ related. I also extract metadata from all mirrored packages, I do not currently publish it because I am only just now getting back on track with the Emacsmirror and there's still a lot of cruft around. But I think that this will eventually be a quite useful resource.

Most of that metadata is extracted from the "main library", the entry point for users so to speak. Unfortunately because this repository contains libraries which can be used independently there's no such entry point. That these libraries do not needlessly depend on one-another is a good thing, but has the unfortunate side-effect that there is no standardized source to extract metadata. (The README does not qualify because, unlike library headers, it is basically free form).

As a result I have to somewhat randomly pick a library from which I extract metadata. I have picked `dired-hacks-utils.el` and as a result these libraries as a unit are now described as "Utilities and helpers for dired-hacks collection". Not really a big deal and if it hadn't come up in another conversation I would probably not even have mentioned it.

For that reason I would recommend that you add `dired-hacks.el`, add a header and copy the contents of the README into the Commentary. You could also require all the other libraries in this new umbrella library, so that users who want it all would only have to require this one library.

**Comment by Fuco1** [comment]
I don't like the idea of having to mirror the readme. I already mirror it between the markdown and the library files (each section for each file is supposed to be in sync), adding third file to sync will be bothersome.

I guess I could write some tool to do that for me, but that again takes time.

I can create the meta-package file which just points to the readme/git URL. Is that OK? (do you use the commentary seciton somehow?)

**Comment by tarsius** [comment]
I do extract the commentary but don't think it necessarily has cover everything that the README covers, but it should be a little longer than the summary (line). Copying just the first paragraph from the readme, linking to that, and mentioning that the libraries can be required individually is enough in my opinion.

**Comment by tarsius** [comment]
Closing this now as it is not terribly important. Just in case that makes a difference, this is how `epkg-describe-package`, which is used by the `borg` package manager describes this package:

```
Dired-Hacks is a mirrored package.

     Summary: Utilities and helpers for dired-hacks collection
    Repopage: https://github.com/Fuco1/dired-hacks
  Mirrorpage: https://github.com/emacsmirror/dired-hacks

        Type: github
     License: GPL-3+
     Updated: 20171229
       Stars: 255
     Authors: Matúš Goljer <matus.goljer@gmail.com>
 Maintainers: Matúš Goljer <matus.goljer@gmail.com>

    Provided: dired-avfs, dired-collapse, dired-filter, dired-hacks-utils,
              dired-images, dired-list, dired-narrow, dired-open, 
              dired-rainbow, dired-ranger, dired-subtree, dired-tagsistant
    Keywords: files

Utilities and helpers for `dired-hacks' collection of dired
improvements.

This package also provides these interactive functions:
* `dired-hacks-next-file' - go to next file, skipping empty and non-file lines
* `dired-hacks-previous-file' - go to previous file, skipping empty
  and non-file lines

See https://github.com/Fuco1/dired-hacks for the entire collection

[-] Dependencies:
 |-[+] cl-lib  builtin  cl-lib
 |-[+] dash  github  dash
 |-[+] delsel  builtin  delsel
 |-[+] eimp  github  eimp
 |-[+] emacs  builtin  dired, dired-aux, dired-x, image-mode
 |-[+] f  github  f
 |-[+] find-dired  builtin  find-dired
 |-[+] grep  builtin  grep
 |-[+] ring  builtin  ring
 |-[+] s  github  s
 `-[+] thingatpt  builtin  thingatpt

[-] Reverse dependencies:
 `-[+] dired-sidebar  github  dired-subtree
```
