### ISSUE TITLE
"This cannot happen" message

### ISSUE THREAD

**Issue by caisah** [Fuco1/dired-hacks#32]
After I use `dired-subtree-insert` on a _dir_, when I call `dired-do-redisplay` (pressing **l** muliple times) I get the message 
`"dired-after-subdir-garbage: This cannot happen"`.

**Comment by Fuco1** [comment]
What's the difference between `l` and `g` (revert)? I've never used `dired-do-redisplay`.

**Comment by caisah** [comment]
I honestly have no idea, but I was just playing around and I found this, so I just reported it :smile:

**Comment by Fuco1** [comment]
Fair enough, thanks :D I'll try to find some time to look into it, but since it's not pressing, it might stick around for a while.
