### ISSUE TITLE
Melpa stable

### ISSUE THREAD

**Issue by nlamirault** [Fuco1/dired-hacks#33]
could you please create a tag to use this package using melpa stable [1].
Thanks

[1] : http://stable.melpa.org/

**Comment by Fuco1** [comment]
I don't think this will work as this same repository hosts 8 different packages.

**Comment by Fuco1** [comment]
If melpa stable can support my layout, please tell me, or call back when they do.

I'm closing to keep the issues list tidy.  If you know how to make this work, please reopen and state the solution.
