### ISSUE TITLE
dired-filter systematically fails with "Symbol's function definition is void: cadddr"

### ISSUE THREAD

**Issue by bgandon** [Fuco1/dired-hacks#35]
When in `dired-mode` with `dired-filter-mode` enabled, any function like `/ h` or `/ .` fails with the message *“Symbol's function definition is void: cadddr”* in the minibuffer.

I first got the issue with Emacs 24.4.1, then upgraded to Emacs 24.5.1 and got the same result.

Looking at Emacs manual, I got the concept of the built-in `car` and `cdr` functions. In my Emacs installation, the four `cxxr` forms are provided by `subr.el`. But the longer `cxxxr` forms can't be found by the help system: `C-h f caddr` fails with "no match", and the same goes for `C-h f cadddr`.

Google helped me to understand that those would be defined by `cl.el`.

So, the solution was: `M-x load-library cl`. Then `dired-filter-mode` started working like a charm!

When reading the `lisp/emacs-lisp/cl.el` file, the header line says: *Compatibility aliases for the old CL library*, and the end of the file suggest that this old CL library might have been deprecated in Emacs 24.4. So I guess the reason why `cadddr` is missing, is a recent evolution of Emacs.

Could you please patch your code to use expanded forms of `cadddr` (which would simply be a `cadr` of `cddr`) so that this compatibility issue doesn't arise anymore?

Regexp-searching `c[ad]\{3,\}r` in your code, I found 8 occurrences. Patching those (and moving away the `.elc` file) resolved the issue in a nice way, without requiring the compatibility library.

Hope this might help others!

**Comment by Fuco1** [comment]
All the cl functions are now included in the `cl` library as `cl-cxxxxr`, all we need is to do is to prefix them.  The cl.el library adds alases form the unprefixed versions to the prefixed versions.

I think better fix would be to rename them and require `cl`.

Ideal solution would be to wrap the accessors with meaningful functions, like `dired-filter-get-name` etc... beacuse now it's quite unobvious.

Can you try to see if adding the prefix works for you?

**Comment by bgandon** [comment]
Yes, indeed. I patched your code again, prefixing with `cl-`, and it works too out of the box!

The `cl` library is already there and doesn't need to be required. Only the old names were missing.

**Comment by Fuco1** [comment]
Don't you want to send a PR? It would help since you already have the code working :)

**Comment by Fuco1** [comment]
Well, `cl` library is loaded probably because soe other package you use loads it. But we still should add `(require 'cl)` on top in case nobody loaded it before.

**Comment by bgandon** [comment]
Ok I just submitted the PR #39 to fix this. Sorry for the delay ;-)
