### ISSUE TITLE
enhancement: allow marking with saved filters

### ISSUE THREAD

**Issue by vapniks** [Fuco1/dired-hacks#37]
Also, prefer to use ```ido-completing-read``` instead of ```completing-read``` for choosing from saved filters

**Comment by Fuco1** [comment]
re completing read mechanism, that is something you should set up as a user, not on the package side.  For me it uses ido for example.

Marking would be cool indeed.

**Comment by vapniks** [comment]
but the only way to do it as a use is to use ```ido-completing-read``` instead of ```completing-read``` for everything. I prefer to use normal ```completing-read``` for many tasks (entering commands for example).

**Comment by Fuco1** [comment]
> but the only way to do it as a use is to use ```ido-completing-read``` instead of ```completing-read``` for everything. I prefer to use normal ```completing-read``` for many tasks (entering commands for example).

In that case I guess you could write a wrapper around the filters
`flet'ting `completing-read` to whatever you wish to use.

PS: at github, inline code is marked with single backtick, not three

**Comment by vapniks** [comment]
no it isn't, I'm looking at the webpage right now

**Comment by Fuco1** [comment]
That's because the comments aren't parsed when I reply with email.  Three ticks are for block code

```
like
so
     lots of code
```

Single ticks `work fine` inline, and in fact it's only due to github being "nonstandard" that it works at all.

    That's because the comments aren't parsed when I reply with email.  Three ticks are for block code
    
    ```
    like
    so
         lots of code
    ```
    
    Single ticks `work fine` inline, and in fact it's only due to github being "nonstandard" that it works at all.

**Comment by vapniks** [comment]
ah ok, `thanks`

**Comment by vapniks** [comment]
I will put a bounty on this when I've sorted out some payment issues

**Comment by vapniks** [comment]
What size bounty would motivate you to fix this?

**Comment by Fuco1** [comment]
After half a year, but done :) Thanks for the suggestion.

By default it is bound on `L` (you might need to re-customize the prefix or restart emacs if you update via package.el)
