### ISSUE TITLE
Is it possible to make dired-ranger work on all files marked in multiple dired buffers?

### ISSUE THREAD

**Issue by QiangF** [Fuco1/dired-hacks#38]
Hello everyone,
There is a question on stackexchange
http://emacs.stackexchange.com/questions/13552/how-to-make-dired-mode-copy-and-move-all-marked-file-in-all-dired-buffer-includi
But when I tried today,  mark in a subfolder doesn't change when I go up one level and come back. Maybe someone here can do that.
Thank you for your consideration!

**Comment by Fuco1** [comment]
`dired-ranger` currently only implements copying and moving, but other operations can be added very easily.  PRs welcome

You can add files to the "stage are" with `dired-ranger-copy` (which we should probably rename to `dired-ranger-stage`).  If you want to then add more files to the same set, use `C-u`.  You can do this from multiple dired buffers.

**Comment by QiangF** [comment]
Thanks for the tip. Works perfectly!
