### ISSUE TITLE
How to do hardlink and softlink on selected files in different folder

### ISSUE THREAD

**Issue by QiangF** [Fuco1/dired-hacks#47]
Hi everyone,
I am wondering if anyone has the same need as me. What I want is a command like dired-ranger-paste but do hardlink and softlink. I am no good at elisp. Maybe someone can implement it.
Thank you!

**Comment by Fuco1** [comment]
Basically just copy-paste `dired-ranger-move` and replace `rename-file` with whatever function emacs uses to link.  Ideally the basic skeleton would be abstracted so people can add these commands easily.

**Comment by QiangF** [comment]
Thank you!
