### ISSUE TITLE
Hide the bar of dired-filter-mode?

### ISSUE THREAD

**Issue by ReneFroger** [Fuco1/dired-hacks#49]
I currently use the [use-package](https://github.com/jwiegley/use-package). 

So `dired-filter` is configured as following: 

```
(use-package dired-filter
    :defer 4
    :config
    (dired-filter-mode))
```

I would like to have it already active, when I open Dired. So I can always filter contents of Dired, if I want, without enabling it every time.

When starting Emacs, I noticed it added the bar " Active filters:  [Omit]" to the top of my scratch buffer, after `dired-filter-mode` gets enabled. I would like to don't see that bar. Is there any way to prevent the bar to popping it up?

**Comment by Fuco1** [comment]
Try customizing `dired-filter-show-filters`.

**Comment by ReneFroger** [comment]
Thanks for your reply. I changed it to the following:

    (use-package dired-filter
        :defer 4
        :config
        (dired-filter-mode)
        (setq dired-filter-show-filters 'nil))

Which didn't help at all. Another suggestion?

**Comment by Fuco1** [comment]
It should probably be just `nil`, other than that I don't know.  Try to go through the available settings (I don't have emacs here now) and see if something looks useful.

If not, we can add a setting.

**Comment by ReneFroger** [comment]
Just checked the source code of `dired-filter`. My Elisp profiency is somewhat limited, I couldn't find any ability to change the bar.

I would love to hear in which way I can find or create such settings.

**Comment by Fuco1** [comment]
`(setq dired-filter-show-filters nil)` works for me.  You have to turn the mode on and off for it to take effect.
