### ISSUE TITLE
Provide visual indication when a dired buffer is narrowed

### ISSUE THREAD

**Issue by glucas** [Fuco1/dired-hacks#50]
It would be useful to have some indication (e.g. in the mode line) when a dired buffer has been filtered using dired-narrow.

**Comment by Fuco1** [comment]
Good idea, but mode line is notoriously difficult to "get right".  People often mod it and the default api is unusable.

The best I can think of is entering a minor mode which would advertize itself... if the user disabled that display they won't see it but then that is not my problem :P

**Comment by glucas** [comment]
That sounds good to me -- I've seen other modes do something similar.

**Comment by Fuco1** [comment]
I pushed a commit, can you see if it works for you?  From my brief testing it seems to work.

**Comment by glucas** [comment]
Looks good. I'd suggest adding a leading space to the name, per the Minor Mode Conventions in the Emacs Lisp manual:

    Here MODE-VARIABLE is the variable that controls enabling of the
    minor mode, and STRING is a short string, starting with a space, to
    represent the mode in the mode line.

Thanks for the quick response on this! It's a handy package.

**Comment by Fuco1** [comment]
Right, thanks for the feedback.
