### ISSUE TITLE
Opening files in external applications

### ISSUE THREAD

**Issue by DamienCassou** [Fuco1/dired-hacks#51]
I wrote https://github.com/DamienCassou/unify-opening to facilitate handling of external applications from Emacs. It leverages the dired mechanism.

https://github.com/thamer/runner is a great package to improve dired way of opening external applications.

**Comment by Fuco1** [comment]
Dired guess is too stupid for my taste, which is why I wrote my own.  I'm not sure it's possible to reconcile it.

If anything, I would try to get a more general and simpler to use way to emacs directly and then press on others to adopt it, dired included.

**Comment by DamienCassou** [comment]
You should really look at [runner](https://github.com/thamer/runner) before implementing anything.
