### ISSUE TITLE
Go to begin and end of dired buffers

### ISSUE THREAD

**Issue by DamienCassou** [Fuco1/dired-hacks#52]
[beginend](https://github.com/DamienCassou/beginend) is a project to redefine the notion of begin and end in some special buffers, dired included. With beginend, `M-<` goes to the first file and `M->` goes to the last file.

**Comment by Fuco1** [comment]
Okey, and what should I do with it? :D

**Comment by Fuco1** [comment]
By the way cool project, I have had similar code in my .emacs for ages with a notice "make this into a package"... I also have redefs for vc, ibuffer, recentf and others.  Maybe I'll send a patch your way.

**Comment by DamienCassou** [comment]
@Fuco1 do whatever you want with it :-). I just wanted to let you know as I thought this was related. If you have any similar code in your projects, we should reuse instead of duplicating each others work.

Please send me patches if you can.

**Comment by Fuco1** [comment]
Not in my projects, just personal config I never turned into a package :P

Thanks for letting me know.
