### ISSUE TITLE
live narrowing: allow the use of up/down/enter keys for interactions or maybe dired-narrowing-mode?

### ISSUE THREAD

**Issue by zeltak** [Fuco1/dired-hacks#54]
Hi Fuco
thx so much for your amazing packages, this finally lets me the opportunity to switch to dired full time as my file manager :)
one thing i really miss from worker/nutlius/spacefm/etc is the ability to quick narrow and choose files. currently in  narrowing as far as i can tell i can quick narrow (filter) but then need to press Enter before i can interact with files. I would love the ability to use the up/down/enter keys to quick exe/interact with files without pressing enter?

Alternatively may i suggest a dired-narrow-mode, where one could enable it with a hotkey/enable at dired startup, where then entering keys would start narrowing mode. (i think sunrise commander has something like this)

thx so much again for all your amazing work

z

**Comment by Fuco1** [comment]
It should be enough to pass a different keymap to `read-from-minibuffer` so it exits the narrowing when you hit arrow keys or some other key (isearch does this for example)

**Comment by zeltak** [comment]
thx for the quick reply fuco, im a bit (well alot ;-)) of a neewb. can you show me an example of how to pass the different keymap  to read-from-minibuffer ?

best

Z

**Comment by Fuco1** [comment]
I've pushed some stuff, set `dired-narrow-exit-action` to "find file" (its a choice option), you can move up/down with arrow keys, you can rebind the actions in `dired-narrow-map`.  I will write up a list of available functions later.

**Comment by zeltak** [comment]
thx

is this what you mean?

(setq dired-narrow-exit-action "find-file")

probably not since this seems to not let me use the arrow keys.

Appreciate the help with this, Happy new years :)

Z

**Comment by Fuco1** [comment]
Open it in customize and pick that option.  Arrows should work regardless, if not restart emacs to reload the package.

**Comment by zeltak** [comment]
Perfect! thx so much, this is pretty cool :)

i just realized i forgot to ask for a related bind (or didnt explain myself correctly :)). 
now that the up/down arrows work well can we have the right arrow launch the action/enter the dir? i wouldn't also mind having ENTER do that but i can see how that may cause problems, but maybe not.
currently i narrow> go up and down > then need to press Enter twice (one to end narrowing and one to preform action/enter dir). would be cooler to save a key stroke (..yeah 1st world problems ;))

thx so much for you time!

best

Z

**Comment by Fuco1** [comment]
If you `(setq dired-narrow-exit-action 'dired-narrow-find-file)` it will enter with the first RET.

You don't use customize much do you? :D

**Comment by zeltak** [comment]
hehe yeah im a neewb as i said, though to be fair when i do customize-group>dired-narrow i dont get any where to choose options just a box to write in the command:
https://paste.xinu.at/XcJ7i/

anyway the dired-narrow-find-file acts exactly as i wanted, i feel complete now ;-)

best

Z

**Comment by Fuco1** [comment]
That's the "choice" widget, you can click on a button next to the field where you enter a command and there will be a pre-set option "use dired-find-file".  It can seema bit confusing if you're not used to the emacs UI.

**Comment by zeltak** [comment]
thx :) this is getting way off topic but i dont seem to have any such choice with any button. i created a short screencast to demonstrate :)
https://paste.xinu.at/Osn/
best

Z

**Comment by Fuco1** [comment]
Right, you have a "mismatch" there (shown in the parens).  What you need to do is to erase customization (through the state button) and then next to the variable name there will be a button ![](http://i.imgur.com/DUSHpPO.png)

**Comment by Fuco1** [comment]
I've also added a function (by default on right arrow) which will descend into a directory and immediately go into filtering mode, so you just type, ->, type, -> to quickly traverse down the hierarchy.

**Comment by zeltak** [comment]
tested and works perfectly, thx!

z

**Comment by Fuco1** [comment]
Okey let's close this, if you have some more ideas open a new issue.  Cheers!
