### ISSUE TITLE
cant get dired-open to work

### ISSUE THREAD

**Issue by zeltak** [Fuco1/dired-hacks#55]
Hi again

im trying to use as many of the extensions you made as possible ;-)

while all other extensions worked as instructed i cant get my head around dired-open. its my understanding that when you configure dired-open (which i dont understand how yet) one could press enter on files and then based on specific file type/extension a user defined action would take place. such as pressing enter on an html file and then firefox opens up. is that correct? if so would you mind giving me a short example on how to configure that (for example the html>firefox thing)

thx!

Z

**Comment by Fuco1** [comment]
You need to change `dired-open-extensions`.  For example, these are the values I use

```
(("exe" . "wine")
 ("docx" . "libreoffice")
 ("doc" . "libreoffice")
 ("xlsx" . "libreoffice")
 ("xls" . "libreoffice")
 ("epub" . "fbreader"))
```

In addition, you can customize what "handlers" are used to decide what to do by changing `dired-open-functions`.  Adding `dired-open-guess-shell-alist` will provide some defaults for many file types, but some people don't like that much so it's not on out of the box.

**Comment by zeltak** [comment]
mmm ok so i tried that , and here is my current config
```
(use-package dired-open
 :ensure t
 :config
 (setq dired-open-extensions
      '(("pdf" . "okular")
        ("mkv" . "vlc")
        ("mp4" . "vlc")
        ("avi" . "vlc")
        ("html" . "firefox")
        ("mp3" . "vlc")
))
 )
```
(note that i have tried also with the custom-variable option with same results, i just prefer it all in my init file)

in any case i still get the html file to open as an html buffer in emacs and pdf files to open in pdf view in emacs. is there something else im missing?

thx!

Z

**Comment by zeltak** [comment]
Just to update that i ended up binding C-enter to dired-open-file and it works great, i can live with that :)
thx!

Z

**Comment by Fuco1** [comment]
When you load `dired-open` it should automatically remap

    (define-key dired-mode-map [remap dired-find-file] 'dired-open-file)

Maybe you had another function bound on `RET`.  I would probably turn it into a minor mode so it doesn't change behaviour "randomly" on load though.

**Comment by habamax** [comment]
Should it work for windows?

At the moment whey press <CR> on a html file I get `Searching for program: No such file or directory, sh`

I have the following config:

```
(use-package dired-open
  :after dired
  :config
  (setq dired-open-extensions
        '(("pdf" . "start")
          ("mkv" . "vlc")
          ("mp4" . "vlc")
          ("avi" . "vlc")
          ("html" . "firefox")
          ("mp3" . "vlc"))))
```

**Comment by habamax** [comment]
If I set `(setq dired-open-use-nohup nil)` then I get vlc running on `mp3` files but actual file is not in the player.

**Comment by Fuco1** [comment]
I'm not sure about windows and I have no access to a windows machine so it's hard to test.  The function responsible is `dired-open--start-process` so that's where I would start looking.

**Comment by habamax** [comment]
So I have come up with the following solution:

```
;; <CR> to open file under cursor in OS
(use-package dired-open
  :after dired
  :config
  (defun haba/dired-open-in-os ()
    "Open file/folder under cursor in OS."
    (interactive)
    (let ((file (ignore-errors (dired-get-file-for-visit))))
      (browse-url (file-truename file))))
  (setq dired-open-functions '(haba/dired-open-in-os)))

```
I guess it should also work for OSX -- will check it tonight.

**Comment by habamax** [comment]
Well, basically it looks like I don't need dired-open. I can just bind/call the function"

```
(use-package dired
  :ensure nil
  :defer t
  :commands (dired dired-jump dired-jump-other-window)
  :bind (("C-x C-j" . dired-jump)
         ("C-x 4 C-j" . dired-jump-other-window)
         :map dired-mode-map
         ("b" . bookmark-jump)
         ("j" . dired-up-directory)
         ("J" . dired-goto-file)
         ("<C-return>" . haba/dired-open-in-os))
  :config
  ;; dired user another dired buffer as destination for copy/move
  (setq dired-dwim-target t)

  (defun haba/dired-open-in-os ()
    "Open file/folder under cursor in OS."
    (interactive)
    (let ((file (ignore-errors (dired-get-file-for-visit))))
      (browse-url (file-truename file)))))

```

Anyway, thanks :)

**Comment by deggers** [comment]
And as of today, you won't even need this function
Calling "treemacs-visit-node-in-external-application" calls for me my defined pdf-opener from the system on a pdf-node.
As of today, its defined in the as typing "o" (open) followed by "e" (externally) on the item you want to open :-)

**Comment by Fuco1** [comment]
Just a note for people coming here later: `treemacs-visit-node-in-external-application` is not built-in so you would still need to install some package.
