### ISSUE TITLE
minibuffer-keyboard-quit not found

### ISSUE THREAD

**Issue by dvzubarev** [Fuco1/dired-hacks#59]
Hi,
I use emacs 24.5.1 with spacemacs 0.105.9 on Ubuntu 15.10.
Steps to reproduce:
1. M-x dired-narrow
2. C-g
3. I get an error "command-execute: Symbol's function definition is void: minibuffer-keyboard-quit"

**Comment by Fuco1** [comment]
Thanks, I'm missing a require for `delsel` package (bundled with emacs)
