### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by agzam** [Fuco1/dired-hacks#64]
I have couple of questions about `dired-rainbow`.

1) How to make it work with Ranger. It doesn't seem to be working in Deer or Ranger (I'm using Spacemacs)
2) How can I tell it to gray out "dot files" - dirs and files that start with dot e.g. ".git" 

Thank you

**Comment by Fuco1** [comment]
Hi.

1) no idea, ranger probably does its own magic
2) currently you can't as this only works with extensions.  You can use `dired-filter` to hide them if you want though... I could probably combine the two somehow.

**Comment by dvzubarev** [comment]
Hi, 
I'm using the following code for coloring dot files `(dired-rainbow-define omit2 "dark gray" "\\.\\(?:.*$\\)")`. It works only for files though. I do not know how to change color of the directories

**Comment by Fuco1** [comment]
Ah, so we already implemented custom matchers :D

Directories are colored in different sequence so that would be harder to get right.  Dired is kind of... unstructured.

**Comment by agzam** [comment]
@dvzubarev that regex doesn't work for me

**Comment by dvzubarev** [comment]
Does any function work for you? For example `(dired-rainbow-define html "Chocolate" ("htm" "html" "xhtml"))`.I had to customize dired-rainbow-date-regexp to get all working.I'm using that code:`(setq dired-rainbow-date-regexp "\\(?:[0-9][0-9]:[0-9][0-9]\\|.[0-9]\\{4\\}\\)")` 09.02.2016, 22:51, "Ag Ibragimov" <notifications@github.com>:@dvzubarev that regex doesn't work for me—Reply to this email directly or view it on GitHub.
