### ISSUE TITLE
emacs elisp checker complains about dired-rainbow-define

### ISSUE THREAD

**Issue by emacsuser123** [Fuco1/dired-hacks#72]
Hi.

I'm using dired-rainbow package in my emacs init.el file, and I like the way I can play around with colours in dired listings thanks to it.

But, whenever I run my elisp-checker on my init.el file, I get the following error:

> error           Forgot to expand macro dired-rainbow-define (emacs-lisp)

I get this error for every line in my init.el using the dired-rainbow-define macro.

This one is the only macro that makes my elisp checker to give an error.
I use other macros, like defhydra, and I get not error at all.

Any idea on how can I get rid of this error?

Thanks a lot.
-Bob

**Comment by Fuco1** [comment]
I'm afraid I have no idea what "your elisp checker" does :(

I suppose the problem is that the macro doesn't define the debug spec.  Could you try to add `(declare (debug t))` as the first form for a temporary solution and report what it gives?

**Comment by emacsuser123** [comment]
Hi.
Well, the elisp checker I'm using is flycheck.

I have added the statement you mentioned as the first form and nothing seems to be reported, though, other than the errors reported by the flycheck package.

Thanks.
-Bob

**Comment by Fuco1** [comment]
Thanks, I will provide a proper debug declaration then (having just `t` is a little bit of a hack).

**Comment by Fuco1** [comment]
I've added the debug forms but this is likely an error with flycheck (well... with Emacs eval model) as it loads things before it knows those forms are macros and then can't expand them.  This happens if you use `eval-after-load` or `use-package` and similar.  Can't be fixed from the package's end.
