### ISSUE TITLE
File already exists, dired-ranger-move aborted move operations for all selected files

### ISSUE THREAD

**Issue by QiangF** [Fuco1/dired-hacks#75]
When I use dired ranger to move a couple of files, if ther is one file with the same name in the destination folder and I choose not to overwrite that file, all following files are not move?
Can you make it behave like all other file managers, let the user to choose overwrite or not for each or for all files?

**Comment by Fuco1** [comment]
Yea this just happened to me couple days ago.  The thing is I have no idea why it happens :D the code clearly loops through all the files and there is no break.

I will check it out.
