### ISSUE TITLE
Readme doesn't render properly

### ISSUE THREAD

**Issue by alphapapa** [Fuco1/dired-hacks#79]
Hey, just FYI, the readme is rendering really awkwardly on GitHub.  A lot of text appears blue, as if linked, but it's not.  Maybe something to do with the `<a ... />` tags.

Have you considered doing the readme as an Org file?  :)

**Comment by Fuco1** [comment]
I'm not seeing any links issues, but I see that the headlines starting with `##` are not fontified properly.

I had some projects with org readmes but the org renderer was terrible back in the days so I switched back to markdown.

They must've changed something because I've noticed other projects also getting these problems.

**Comment by Silex** [comment]
Well, looking at the source https://raw.githubusercontent.com/Fuco1/dired-hacks/master/README.md the markdown looks very weird. Why are there html links in there?

**Comment by Silex** [comment]
Yep, looks like removing those fixes it:

https://github.com/Fuco1/dired-hacks/blob/update-readme/README.md

Now before merging the PR, we need to think about the implications, maybe change some links.

**Comment by Fuco1** [comment]
By links you mean `<a name="packages" />` and similar? Those are there to make the TOC "navigate" properly.  This is a script I hacked together 5 years ago, maybe there are better markdown toc tools these days?

Anyone knows how to a) generate toc and b) make clickable links to the sections?

**Comment by alphapapa** [comment]
Well, it's not markdown, but I'd suggest converting the MD to Org with Pandoc, then using `toc-org` to insert the table of contents.  Works great for my readmes.

**Comment by Silex** [comment]
Using pandoc is nice, but if the goal is just to generate a TOC simply use https://github.com/ekalinin/github-markdown-toc or similar.

**Comment by alphapapa** [comment]
Pandoc was for the one-time conversion from Markdown to Org.  The TOC is then generated automatically within Emacs in the `before-save-hook` by `toc-org`.

**Comment by Silex** [comment]
Ah, automatic generation looks interesting.

It's up to @Fuco1 to switch to org if he wants to.

**Comment by Fuco1** [comment]
I think there isn't much to gain by switching to org, so I'll go with #80.
