### ISSUE TITLE
Support for getting file size

### ISSUE THREAD

**Issue by rgrinberg** [Fuco1/dired-hacks#84]
The little snippet in this repository seems like a pretty candidate for this repo:

https://oremacs.com/2015/01/12/dired-file-size/

I've often wanted something like this.

**Comment by Fuco1** [comment]
This can be achieved by marking the files then hitting `! du -sh *`.  I think it's not that useful if we only add it as a command (as it would also be pretty undiscoverable).  There is currently no "grab-bag" of functions but maybe we can create such a package.

I'll close this for now.
