### ISSUE TITLE
[dired-collapse] First of the collapsed dirs shows up indented a bit to the left

### ISSUE THREAD

**Issue by kaushalmodi** [Fuco1/dired-hacks#89]
Hello,

Thank you for implementing this feature.

The below screencaps explain the issue very well:

**Before enabling `dired-collapse-mode`**
![image](https://user-images.githubusercontent.com/3578197/28290587-037ab37e-6b15-11e7-9144-5e6c7f265961.png)

**After enabling `dired-collapse-mode`**
![image](https://user-images.githubusercontent.com/3578197/28290612-163dcd3e-6b15-11e7-9c3c-a968db2ab523.png)
Note that the first collapsed dir "archetypes" is indented a bit to the left, because the size column has the wrong spacing. Surprisingly this happens only for the first collapsed dir.

**Comment by kaushalmodi** [comment]
Another one:

![image](https://user-images.githubusercontent.com/3578197/28290856-0aa0e9ce-6b16-11e7-8dff-71e8ea4ebb68.png)

It looks as if the size shows the size of the file in the collapsed dir. But the size column width is not filled with spaces to match the max size col width in the parent dir.

**Comment by Fuco1** [comment]
Hmm, it should be filled

![](http://i.imgur.com/dcoZMUi.png)

I suspect this depends on the version of `ls` you have installed as well as other flags for dired enabled.  It might not be as simple as I hoped to make this consistent :/

**Comment by Fuco1** [comment]
Oh I see, the issue is that you don't have the group owner shown.  So it thinks the size is the group and the date is the size and calculates the offsets badly :/

I didn't know you could hide the group owner column.

**Comment by kaushalmodi** [comment]
Oh, right..  I am is my the `-G` switch to present the redundant *$USER $USER* in the display. 

```
    ;; Dired listing switches
    ;;  -a : Do not ignore entries starting with .
    ;;  -l : Use long listing format.
    ;;  -G : Do not print group names like 'users'
    ;;  -h : Human-readable sizes like 1K, 234M, ..
    ;;  -v : Do natural sort .. so the file names starting with . will show up first.
    ;;  -F : Classify filenames by appending '*' to executables,
    ;;       '/' to directories, etc.
    (setq dired-listing-switches "-alGhvF --group-directories-first") ; default: "-al"
```

So you might need to look at the value of `dired-listing-switches` before recreating the row?

**Comment by Fuco1** [comment]
I respect the switches on the reinsert (as you can see they don't have the group shown) but I do not respect them when I'm calculating the column offsets.  That will need to be fixed.

**Comment by kaushalmodi** [comment]
Hello, sorry to say, but I still see this issue.. it happens for all the rows where the *size* takes up less than 4 characters:

![image](https://user-images.githubusercontent.com/3578197/31455457-8f3c8302-ae85-11e7-8ad2-0e9c398bb3b7.png)

See **46K**, **733** above.

**Comment by kaushalmodi** [comment]
@Fuco1 Please ignore the earlier message.. turns out I forgot to eval the updated/fixed version :man_facepalming:
