### ISSUE TITLE
[collapse]: Missing autoload cookie

### ISSUE THREAD

**Issue by mattiasb** [Fuco1/dired-hacks#90]
I think `dired-collapse-mode` is missing an auto-cookie. :)

Neat mode!

**Comment by marcowahl** [comment]
I agree with mattiasb's comment in every aspect.

**Comment by Fuco1** [comment]
I agree as well :D Patches welcome (I'm currently at work, can't really fix it now)

**Comment by Fuco1** [comment]
Closed in #91
