### ISSUE TITLE
[dired-collapse] seems to misbehave with inserted directories

### ISSUE THREAD

**Issue by zellerin** [Fuco1/dired-hacks#92]
Hi,

Thanks for implementing this.  Following behaviour is probably not intuitive, though:

I have this directory with subdirs, shown without collapsing, with one subdir inserted (`dired-insert-subdir`)
![no-collapse](https://user-images.githubusercontent.com/153838/28338437-402e14ce-6c09-11e7-9d8b-dac36ae34737.png)

When collapsed, the inserted subdir has all entries prefixed with its name:
![collapse](https://user-images.githubusercontent.com/153838/28338574-acd232e0-6c09-11e7-84f8-196536a7e75c.png)

and when you try to visit any entry in the subdirectory, you get 'dired-get-file-for-visit: File no longer exists; type ‘g’ to update Dired buffer'.

Turning dired-collapse off returns all to  working-as-expected state.

Observed in current Melpa version.

**Comment by Fuco1** [comment]
Should be fixed now.
