### ISSUE TITLE
[dired-collapse] doesn't respect `dired-omit-mode'

### ISSUE THREAD

**Issue by matthewbauer** [Fuco1/dired-hacks#95]
The rules for `dired-omit-mode' aren't being applied to files collapsed under dired-collapse-mode.

**Comment by Fuco1** [comment]
Hm.  Yea, I stopped using it in favour of `dired-filter` with the `omit` filter enabled.  But I'm not sure if that works either now that you mention it.

It shouldn't be terribly difficult to fix, I'll look into it.  Thanks for the report.

**Comment by Fuco1** [comment]
This was fixed in #210
