### ISSUE TITLE
[dired-collapse] large link count for inner directory causes incorrect user-column

### ISSUE THREAD

**Issue by kushal-kumaran** [Fuco1/dired-hacks#97]
If an inner directory has a link count with a larger number of digits than the parent, `user-column` and `group-column` is not correct for that row.  This is because those values are calculated for the first row in the directory listing for the current directory.  The script below can create a directory tree that demostrates the problem:

    #!/bin/bash

    mkdir a
    mkdir b
    mkdir b/c
    for ((i=1;i<=100;i++)) do
      mkdir b/c/d$i
    done

Here, the directory `b/c` has a three digit link count, while the others have a two-digit link count.  This causes the replacement of `b` with `b/c` to cause its user and group columns to be misaligned.

**Comment by Fuco1** [comment]
I've switched to using `dired-align-file` which is a built-in function and quite reliable.  However it only works when we are expanding not shirnking the line.  It seems to be quite complex and solving the above case would be really difficult to do reliably, so I'm going to close this as a wontfix.
